remove {{}} usage as it makes templating a pain vs normal shell equivs, also fixup stch_dir to take multiple args

diff --git a/stch/stch_dir b/stch/stch_dir
--- a/stch/stch_dir
+++ b/stch/stch_dir
@@ -1,16 +1,16 @@
 #!/bin/sh
 
-template_file() {
-    printf "Templating stch file %s..." "$1"
-    # Overwriting on failure is intended
-    if stch < "$1" > "$2"; then
-        echo "done"
-    else
-        echo "failed! for $1" >&2
-        exit 1
+find "$@" -depth -name "*.stch" | while read -r f; do
+    dir="${f%/*}"
+    bname="${f%.*}"
+    if [ -w "$dir" ]; then
+        printf "Templating stch file %s..." "$f"
+        # Overwriting on failure is intended
+        if stch < "$f" > "$bname"; then
+            echo "done"
+        else
+            echo "failed! for $f" >&2
+            exit 1
+        fi
     fi
-}
-
-find "${1:-/etc}" -depth -name "*.stch" | while read -r f; do
-    template_file "$f" "${f%.*}"
 done
